#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# For reference:
# - env: The construction environment.
# - target: The target build type (template_debug, template_release, editor).
# - platform: The target platform (linux, windows, macos, android, ios, web).

# Define the name of the library
libname = "libsounds"

# Sources to compile
sources = [
    "src/register_types.cpp",
    "src/machi_sound_cue.cpp",
    "src/machi_sound_manager.cpp",
]

# Include directories
env.Append(CPPPATH=["src"])

# Tweak the output filename
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/{}.{}.{}.framework/{}".format(libname, env["platform"], env["target"], libname),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
