#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# Define the name of the library
libname = "libsounds"

# Sources to compile
sources = [
    "src/register_types.cpp",
    "src/sound_cue.cpp",
    "src/sound_manager.cpp",
    "src/sound_server.cpp",
]

# Include directories
env.Append(CPPPATH=["src"])

# Tweak the output filename
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/{}.{}.{}.framework/{}".format(libname, env["platform"], env["target"], libname),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
