#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# Define the name of the library
libname = "libbehaviortree"

# Sources to compile
sources = [
    "src/register_types.cpp",
    "src/machi_bt_node.cpp",
    "src/machi_bt_composite.cpp",
    "src/machi_bt_decorator.cpp",
    "src/machi_bt_task.cpp",
    "src/machi_bt_player.cpp",
    "src/machi_blackboard.cpp",
    "src/machi_behavior_tree.cpp",
]

# Include directories
env.Append(CPPPATH=["src"])

# Tweak the output filename
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/{}.{}.{}.framework/{}".format(libname, env["platform"], env["target"], libname),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
