#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# For reference:
# - env.Append(CPPPATH=["src/"])
# - env.Append(LIBS=["..."])

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/osmo.{}.{}.framework/osmo.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/osmo{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
